<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-09-11T14:16:53Z" name="Default suite" finished-at="2023-09-11T14:18:28Z" duration-ms="94564">
    <groups>
    </groups>
    <test started-at="2023-09-11T14:16:53Z" name="Default test" finished-at="2023-09-11T14:18:28Z" duration-ms="94564">
      <class name="com.bk.testScripts.loginPage.ManagePatientTest">
        <test-method is-config="true" signature="beforeSuite()[pri:0, instance:com.bk.testScripts.loginPage.ManagePatientTest@10cf09e8]" started-at="2023-09-11T19:46:53Z" name="beforeSuite" finished-at="2023-09-11T19:46:53Z" duration-ms="343" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeSuite -->
        <test-method is-config="true" signature="beforeTest()[pri:0, instance:com.bk.testScripts.loginPage.ManagePatientTest@10cf09e8]" started-at="2023-09-11T19:46:53Z" name="beforeTest" finished-at="2023-09-11T19:47:01Z" duration-ms="7232" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeTest -->
        <test-method is-config="true" signature="beforeMethod(java.lang.reflect.Method)[pri:0, instance:com.bk.testScripts.loginPage.ManagePatientTest@10cf09e8]" started-at="2023-09-11T19:47:01Z" name="beforeMethod" finished-at="2023-09-11T19:47:09Z" duration-ms="8155" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.bk.testScripts.loginPage.ManagePatientTest.verifyNoOfOrganization() throws java.lang.InterruptedException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method signature="verifyNoOfOrganization()[pri:0, instance:com.bk.testScripts.loginPage.ManagePatientTest@10cf09e8]" started-at="2023-09-11T19:47:09Z" name="verifyNoOfOrganization" finished-at="2023-09-11T19:48:22Z" duration-ms="73693" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at com.bk.testScripts.loginPage.ManagePatientTest.verifyNoOfOrganization(ManagePatientTest.java:73)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyNoOfOrganization -->
        <test-method is-config="true" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:com.bk.testScripts.loginPage.ManagePatientTest@10cf09e8]" started-at="2023-09-11T19:48:22Z" name="afterMethod" finished-at="2023-09-11T19:48:23Z" duration-ms="651" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=verifyNoOfOrganization status=FAILURE method=ManagePatientTest.verifyNoOfOrganization()[pri:0, instance:com.bk.testScripts.loginPage.ManagePatientTest@10cf09e8] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method is-config="true" signature="afterTest()[pri:0, instance:com.bk.testScripts.loginPage.ManagePatientTest@10cf09e8]" started-at="2023-09-11T19:48:23Z" name="afterTest" finished-at="2023-09-11T19:48:28Z" duration-ms="4799" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterTest -->
      </class> <!-- com.bk.testScripts.loginPage.ManagePatientTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
